apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: sandbox-subscription
  namespace: learnflow
spec:
  pubsubname: pubsub
  topic: learnflow.code_execution
  route: /execute
  scopes:
    - code-sandbox-service
