apiVersion: v1
kind: Service
metadata:
  name: learnflow-frontend-svc
  namespace: learnflow
spec:
  type: NodePort
  selector:
    app: learnflow-frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
