apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: exercise-subscription
  namespace: learnflow
spec:
  pubsubname: pubsub
  topic: learnflow.exercise
  route: /exercise
  scopes:
    - exercise-service
