apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: learnflow-state
  namespace: learnflow
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: dapr-postgres-conn
      key: connectionString
  - name: tableName
    value: "dapr_state"
  - name: schema
    value: "public"
