apiVersion: v1
kind: Service
metadata:
  name: concepts-service
  namespace: learnflow
  labels:
    app: concepts-service
spec:
  selector:
    app: concepts-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP
