#!/usr/bin/env python3
"""
agents-md-gen: Generate AGENTS.md for any repository.
MCP Code Execution Pattern: script does all work, returns minimal output.
"""
import os
import sys
from pathlib import Path

SKIP_DIRS = {'.git', 'node_modules', '__pycache__', '.next', 'dist', 'build', '.venv', 'venv'}
MAX_DEPTH = 3


def build_tree(root: Path, depth: int = 0) -> list[str]:
    if depth >= MAX_DEPTH:
        return []
    lines = []
    try:
        entries = sorted(root.iterdir(), key=lambda p: (p.is_file(), p.name))
    except PermissionError:
        return []
    for entry in entries:
        if entry.name.startswith('.') and entry.name not in {'.claude', '.specify'}:
            continue
        if entry.name in SKIP_DIRS:
            continue
        indent = '  ' * depth
        if entry.is_dir():
            lines.append(f"{indent}{entry.name}/")
            lines.extend(build_tree(entry, depth + 1))
        else:
            lines.append(f"{indent}{entry.name}")
    return lines


def read_readme_excerpt(root: Path) -> str:
    for name in ('README.md', 'readme.md', 'README.txt'):
        p = root / name
        if p.exists():
            lines = p.read_text(encoding='utf-8', errors='ignore').splitlines()
            excerpt = ' '.join(lines[:5]).strip()
            return excerpt[:200] if excerpt else 'No description available.'
    return 'No README found.'


def detect_stack(root: Path) -> list[str]:
    stack = []
    if (root / 'package.json').exists():
        stack.append('Node.js/JavaScript')
    if list(root.glob('*.py')) or (root / 'requirements.txt').exists():
        stack.append('Python')
    if (root / 'Dockerfile').exists() or list(root.glob('**/Dockerfile')):
        stack.append('Docker')
    if list(root.glob('**/*.yaml')) or list(root.glob('**/*.yml')):
        stack.append('Kubernetes/Helm (YAML manifests detected)')
    if (root / '.claude').exists():
        stack.append('Claude Code (Skills)')
    return stack or ['Unknown']


def main():
    root = Path.cwd()
    readme = read_readme_excerpt(root)
    tree = build_tree(root)
    stack = detect_stack(root)

    repo_name = root.name

    content = f"""# AGENTS.md — {repo_name}

> Auto-generated by agents-md-gen skill. Update by re-running the skill.

## Purpose

{readme}

## Repository Structure

```
{chr(10).join(tree[:60])}
```

## Technology Stack

{chr(10).join(f'- {s}' for s in stack)}

## Conventions

- **Skills**: All skills in `.claude/skills/<name>/SKILL.md` + `scripts/`
- **Commits**: `<Agent>: <action> using <skill-name> skill`
- **No manual code**: All application code generated by AI agents via skills
- **Token budget**: SKILL.md ≤ 150 tokens; scripts return ≤ 30 tokens of output
- **Cross-agent**: Same SKILL.md works on Claude Code, Goose, and OpenAI Codex

## Agent Usage

### Triggering a skill (Claude Code)
```
claude "Deploy Kafka using kafka-k8s-setup skill"
```

### Triggering a skill (Goose)
```
goose "Deploy Kafka using kafka-k8s-setup skill"
```

### Available Skills

| Skill | Purpose |
|-------|---------|
| agents-md-gen | Generate this AGENTS.md file |
| k8s-foundation | Verify cluster health, create namespaces |
| kafka-k8s-setup | Deploy Apache Kafka via Helm |
| postgres-k8s-setup | Deploy PostgreSQL via Helm + run migrations |
| fastapi-dapr-agent | Scaffold FastAPI + Dapr microservice |
| nextjs-k8s-deploy | Scaffold and deploy Next.js frontend |
| mcp-code-execution | MCP token-efficient data access pattern |
| docusaurus-deploy | Build and deploy Docusaurus documentation |

## Environment Requirements

- Minikube running (`minikube start --cpus=4 --memory=8192`)
- kubectl configured
- Helm 3+ installed
- Claude Code or Goose installed
- Python 3.12+
"""

    output_path = root / 'AGENTS.md'
    output_path.write_text(content, encoding='utf-8')

    sections = ['Purpose', 'Repository Structure', 'Technology Stack',
                'Conventions', 'Agent Usage']
    print(f"✓ AGENTS.md generated ({len(sections)} sections, {len(tree)} paths indexed)")


if __name__ == '__main__':
    main()
