#!/usr/bin/env python3
"""
fastapi-dapr-agent: scaffold.py
Generate a complete FastAPI + Dapr microservice from templates.
MCP Code Execution Pattern: all work done here, returns minimal output.
"""
import argparse
import os
import sys
from pathlib import Path

TEMPLATES = {
    "main.py": '''"""
{service_name} service — LearnFlow AI Agent
Generated by fastapi-dapr-agent skill.
"""
from fastapi import FastAPI, Request
from dapr.ext.fastapi import DaprApp
import httpx
import os
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("{service_name}")

app = FastAPI(title="{service_name} Service")
dapr_app = DaprApp(app)

SERVICE_NAME = "{service_name}"
DAPR_PORT = int(os.environ.get("DAPR_HTTP_PORT", 3500))


@app.get("/health")
async def health():
    return {{"status": "ok", "service": SERVICE_NAME}}


@dapr_app.subscribe(pubsub="{pubsub_topic}", topic="tutor-requests")
async def handle_tutor_request(event: Request):
    body = await event.json()
    logger.info(f"{{SERVICE_NAME}} received event: {{body.get('intent', 'unknown')}}")
    # TODO: implement {service_name} logic
    return {{"success": True}}
''',

    "requirements.txt": '''fastapi==0.110.0
uvicorn[standard]==0.27.1
dapr-ext-fastapi==1.13.0
httpx==0.27.0
''',

    "Dockerfile": '''FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
''',

    "k8s/deployment.yaml": '''apiVersion: apps/v1
kind: Deployment
metadata:
  name: {service_name}
  namespace: learnflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {service_name}
  template:
    metadata:
      labels:
        app: {service_name}
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "{service_name}"
        dapr.io/app-port: "8000"
        dapr.io/log-level: "info"
    spec:
      containers:
      - name: {service_name}
        image: {service_name}:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
''',

    "k8s/service.yaml": '''apiVersion: v1
kind: Service
metadata:
  name: {service_name}
  namespace: learnflow
spec:
  selector:
    app: {service_name}
  ports:
  - port: 8000
    targetPort: 8000
''',

    "dapr/subscription.yaml": '''apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: {service_name}-subscription
  namespace: learnflow
spec:
  pubsubname: kafka-pubsub
  topic: tutor-requests
  route: /tutor-requests
''',
}


def scaffold(service_name: str, output_dir: Path):
    output_dir.mkdir(parents=True, exist_ok=True)

    # Determine pubsub topic
    pubsub_topic = "tutor-requests"
    if service_name == "triage":
        pubsub_topic = "student-events"

    files_created = 0
    for filepath, template in TEMPLATES.items():
        content = template.format(
            service_name=service_name,
            pubsub_topic=pubsub_topic,
        )
        full_path = output_dir / filepath
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content, encoding='utf-8')
        files_created += 1

    return files_created


def main():
    parser = argparse.ArgumentParser(description="Scaffold FastAPI+Dapr service")
    parser.add_argument("--service-name", required=True,
                        help="Service name (e.g., triage, concepts, debug)")
    parser.add_argument("--output-dir", default=None,
                        help="Output directory (default: learnflow-app/services/<name>-service)")
    args = parser.parse_args()

    service_name = args.service_name.lower().replace(" ", "-")
    if args.output_dir:
        output_dir = Path(args.output_dir)
    else:
        output_dir = Path("learnflow-app/services") / f"{service_name}-service"

    count = scaffold(service_name, output_dir)
    print(f"✓ Scaffolded {service_name}-service ({count} files) at {output_dir}")


if __name__ == "__main__":
    main()
